architecture_config:
  model: CISTGCN_eval
  model_params:
    input_n: 10
    joints: 18
    output_n: 25
    n_txcnn_layers: 4
    txc_kernel_size: 3
    reduction: 8
    hidden_dim: 64
    input_gcn:
      model_complexity:
        - 32
        - 32
        - 32
        - 32
      interpretable:
        - true
        - true
        - true
        - true
        - true
    output_gcn:
      model_complexity:
        - 3
      interpretable:
        - true
    clipping: 15
general_config:
  data_dir: ../data/amass/
  experiment_name: benchmark
  load_model_path: 'ckpts/CISTGCN_M32_AMASS.tar'
  log_path: logdir/
  model_name_rel_path: CISTGCN-benchmark
  save_all_intermediate_models: false
  save_models: true
  tensorboard:
    num_mesh: 4
learning_config:
  WarmUp: 100
  normalize: false
  dropout: 0.1
  weight_decay: 1e-4
  epochs: 50
  lr: 0.01
  #  max_norm: 3
  scheduler:
    type: StepLR
    params:
      step_size: 1100
      gamma: 0.8
  loss:
    weights: ""
    type: "mpjpe"
evaluation_config:
  excel_path: "" # write here the name you need. Otherwise, emphy for default name and path.
  outputs_path: "" # if empty uses the model path as default (replacing everything inside) 
  sets:
    - original_test:
        classes:
          - "all"
        evaluate:
          - metrics
          # - samples
        visualization:
          action_batch_samples: 2 # plot number of 2 samples per action batch. HINT: every figure could take a time.
          repeat: 2 # number of times that the figure will be repeated.
          mode: "single" # single or multi
          plot_joints: true # plot joint number of figure
    # - test:
    #     classes:
    #       - "all"
    #     evaluate:
    #       - metrics
    #       - samples
    #     visualization:
    #       action_batch_samples: 16 # plot number of 2 samples per action batch. HINT: every figure could take a time.
    #       repeat: 2 # number of times that the figure will be repeated.
    #       mode: "single" # single or multi
    #       plot_joints: true # plot joint number of figure
    # - full_original_test:
    #     classes:
    #       - "all"
    #     evaluate:
    #       - metrics
    # - train:
    #     classes:
    #       - "all"
    #     evaluate:
    #       - metrics
environment_config:
  actions: all
  protocol: "pro3" # 'pro1: common action split;  0-6: single action split; pro3: unseen action split'
  evaluate_from: 0
  is_norm: true
  job: 0
  sample_rate: 2
  return_all_joints: true
  save_grads: false
  test_batch: 256
  train_batch: 256
meta_config:
  comment: Adding Benchmarking for H3.6M, AMASS, CMU and 3DPW, ExPI on our new architecture
  project: Attention
  task: 3d motion prediction on 18, 22 and 25 joints testing on 18 and 32 joints
  version: 0.1.3
